# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_line_item_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='line_item_total',
            new_name='item_total',
        ),
    ]
