# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_prductimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrductImage',
            new_name='ProductImage',
        ),
    ]
